#!/usr/bin/env bash

declare -x MONGODB_PERFORM_REPAIR
[[ -z "${MONGODB_PERFORM_REPAIR}" ]] && MONGODB_PERFORM_REPAIR="false"

declare -x MONGODB_PERFORM_UPGRADE
[[ -z "${MONGODB_PERFORM_UPGRADE}" ]] && MONGODB_PERFORM_UPGRADE="true"

declare -x MONGODB_ROOT_USERNAME
[[ -z "${MONGODB_ROOT_USERNAME}" ]] && MONGODB_ROOT_USERNAME=""

declare -x MONGODB_ROOT_PASSWORD
[[ -z "${MONGODB_ROOT_PASSWORD}" ]] && MONGODB_ROOT_PASSWORD=""

declare -x MONGODB_AUTH_DB
[[ -z "${MONGODB_AUTH_DB}" ]] && MONGODB_AUTH_DB="admin"

declare -x MONGODB_USERNAME
[[ -z "${MONGODB_USERNAME}" ]] && MONGODB_USERNAME=""

declare -x MONGODB_PASSWORD
[[ -z "${MONGODB_PASSWORD}" ]] && MONGODB_PASSWORD=""

declare -x MONGODB_DATABASE
[[ -z "${MONGODB_DATABASE}" ]] && MONGODB_DATABASE=""

declare -x MONGODB_CONFIG
[[ -z "${MONGODB_CONFIG}" ]] && MONGODB_CONFIG=""

declare -x MONGODB_VERBOSE
[[ -z "${MONGODB_VERBOSE}" ]] && MONGODB_VERBOSE="false"

declare -x MONGODB_QUIET
[[ -z "${MONGODB_QUIET}" ]] && MONGODB_QUIET="false"

declare -x MONGODB_IPV6
[[ -z "${MONGODB_IPV6}" ]] && MONGODB_IPV6="false"

declare -x MONGODB_MAX_CONNS
[[ -z "${MONGODB_MAX_CONNS}" ]] && MONGODB_MAX_CONNS=""

declare -x MONGODB_TIMESTAMP_FORMAT
[[ -z "${MONGODB_TIMESTAMP_FORMAT}" ]] && MONGODB_TIMESTAMP_FORMAT=""

declare -x MONGODB_KEY_FILE
[[ -z "${MONGODB_KEY_FILE}" ]] && MONGODB_KEY_FILE=""

declare -x MONGODB_NOAUTH
[[ -z "${MONGODB_NOAUTH}" ]] && MONGODB_NOAUTH="false"

declare -x MONGODB_SET_PARAMETER
[[ -z "${MONGODB_SET_PARAMETER}" ]] && MONGODB_SET_PARAMETER=""

declare -x MONGODB_HTTPINTERFACE
[[ -z "${MONGODB_HTTPINTERFACE}" ]] && MONGODB_HTTPINTERFACE="false"

declare -x MONGODB_TRANSITION_TO_AUTH
[[ -z "${MONGODB_TRANSITION_TO_AUTH}" ]] && MONGODB_TRANSITION_TO_AUTH="false"

declare -x MONGODB_CLUSTER_AUTH_MODE
[[ -z "${MONGODB_CLUSTER_AUTH_MODE}" ]] && MONGODB_CLUSTER_AUTH_MODE=""

declare -x MONGODB_NETWORK_MESSAGE_COMPRESSORS
[[ -z "${MONGODB_NETWORK_MESSAGE_COMPRESSORS}" ]] && MONGODB_NETWORK_MESSAGE_COMPRESSORS=""

declare -x MONGODB_AUTH
[[ -z "${MONGODB_AUTH}" ]] && MONGODB_AUTH="false"

declare -x MONGODB_JSONP
[[ -z "${MONGODB_JSONP}" ]] && MONGODB_JSONP="false"

declare -x MONGODB_REST
[[ -z "${MONGODB_REST}" ]] && MONGODB_REST="false"

declare -x MONGODB_SLOWMS
[[ -z "${MONGODB_SLOWMS}" ]] && MONGODB_SLOWMS=""

declare -x MONGODB_PROFILE
[[ -z "${MONGODB_PROFILE}" ]] && MONGODB_PROFILE=""

declare -x MONGODB_CPU
[[ -z "${MONGODB_CPU}" ]] && MONGODB_CPU="false"

declare -x MONGODB_NO_INDEX_BUILD_RETRY
[[ -z "${MONGODB_NO_INDEX_BUILD_RETRY}" ]] && MONGODB_NO_INDEX_BUILD_RETRY="false"

declare -x MONGODB_NOSCRIPTING
[[ -z "${MONGODB_NOSCRIPTING}" ]] && MONGODB_NOSCRIPTING="false"

declare -x MONGODB_NOTABLESCAN
[[ -z "${MONGODB_NOTABLESCAN}" ]] && MONGODB_NOTABLESCAN="false"

declare -x MONGODB_OPLOG_SIZE
[[ -z "${MONGODB_OPLOG_SIZE}" ]] && MONGODB_OPLOG_SIZE=""

declare -x MONGODB_REPL_SET
[[ -z "${MONGODB_REPL_SET}" ]] && MONGODB_REPL_SET=""

declare -x MONGODB_REPL_INDEX_PREFETCH
[[ -z "${MONGODB_REPL_INDEX_PREFETCH}" ]] && MONGODB_REPL_INDEX_PREFETCH=""

declare -x MONGODB_ENABLE_MAJORITY_READ_CONCERN
[[ -z "${MONGODB_ENABLE_MAJORITY_READ_CONCERN}" ]] && MONGODB_ENABLE_MAJORITY_READ_CONCERN="false"

declare -x MONGODB_CONFIGSVR
[[ -z "${MONGODB_CONFIGSVR}" ]] && MONGODB_CONFIGSVR="false"

declare -x MONGODB_SHARDSVR
[[ -z "${MONGODB_SHARDSVR}" ]] && MONGODB_SHARDSVR="false"

declare -x MONGODB_SSL_ON_NORMAL_PORTS
[[ -z "${MONGODB_SSL_ON_NORMAL_PORTS}" ]] && MONGODB_SSL_ON_NORMAL_PORTS="false"

declare -x MONGODB_SSL_MODE
[[ -z "${MONGODB_SSL_MODE}" ]] && MONGODB_SSL_MODE=""

declare -x MONGODB_SSL_PEM_KEY_FILE
[[ -z "${MONGODB_SSL_PEM_KEY_FILE}" ]] && MONGODB_SSL_PEM_KEY_FILE=""

declare -x MONGODB_SSL_PEM_KEY_PASSWORD
[[ -z "${MONGODB_SSL_PEM_KEY_PASSWORD}" ]] && MONGODB_SSL_PEM_KEY_PASSWORD=""

declare -x MONGODB_SSL_CLUSTER_FILE
[[ -z "${MONGODB_SSL_CLUSTER_FILE}" ]] && MONGODB_SSL_CLUSTER_FILE=""

declare -x MONGODB_SSL_CLUSTER_PASSWORD
[[ -z "${MONGODB_SSL_CLUSTER_PASSWORD}" ]] && MONGODB_SSL_CLUSTER_PASSWORD=""

declare -x MONGODB_SSL_CA_FILE
[[ -z "${MONGODB_SSL_CA_FILE}" ]] && MONGODB_SSL_CA_FILE=""

declare -x MONGODB_SSL_CRL_FILE
[[ -z "${MONGODB_SSL_CRL_FILE}" ]] && MONGODB_SSL_CRL_FILE=""

declare -x MONGODB_SSL_DISABLED_PROTOCOLS
[[ -z "${MONGODB_SSL_DISABLED_PROTOCOLS}" ]] && MONGODB_SSL_DISABLED_PROTOCOLS=""

declare -x MONGODB_SSL_WEAK_CERTIFICATE_VALIDATION
[[ -z "${MONGODB_SSL_WEAK_CERTIFICATE_VALIDATION}" ]] && MONGODB_SSL_WEAK_CERTIFICATE_VALIDATION=""

declare -x MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES
[[ -z "${MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES}" ]] && MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES="false"

declare -x MONGODB_SSL_ALLOW_INVALID_HOSTNAMES
[[ -z "${MONGODB_SSL_ALLOW_INVALID_HOSTNAMES}" ]] && MONGODB_SSL_ALLOW_INVALID_HOSTNAMES="false"

declare -x MONGODB_SSL_ALLOW_INVALID_CERTIFICATES
[[ -z "${MONGODB_SSL_ALLOW_INVALID_CERTIFICATES}" ]] && MONGODB_SSL_ALLOW_INVALID_CERTIFICATES="false"

declare -x MONGODB_SSL_FIPS_MODE
[[ -z "${MONGODB_SSL_FIPS_MODE}" ]] && MONGODB_SSL_FIPS_MODE="false"

declare -x MONGODB_STORAGE_ENGINE
[[ -z "${MONGODB_STORAGE_ENGINE}" ]] && MONGODB_STORAGE_ENGINE=""

declare -x MONGODB_DBPATH
[[ -z "${MONGODB_DBPATH}" ]] && MONGODB_DBPATH="/var/lib/mongodb"

declare -x MONGODB_DIRECTORYPERDB
[[ -z "${MONGODB_DIRECTORYPERDB}" ]] && MONGODB_DIRECTORYPERDB="false"

declare -x MONGODB_NOPREALLOC
[[ -z "${MONGODB_NOPREALLOC}" ]] && MONGODB_NOPREALLOC="false"

declare -x MONGODB_NSSIZE
[[ -z "${MONGODB_NSSIZE}" ]] && MONGODB_NSSIZE=""

declare -x MONGODB_QUOTA
[[ -z "${MONGODB_QUOTA}" ]] && MONGODB_QUOTA="false"

declare -x MONGODB_QUOTA_FILES
[[ -z "${MONGODB_QUOTA_FILES}" ]] && MONGODB_QUOTA_FILES=""

declare -x MONGODB_SMALLFILES
[[ -z "${MONGODB_SMALLFILES}" ]] && MONGODB_SMALLFILES="false"

declare -x MONGODB_SYNCDELAY
[[ -z "${MONGODB_SYNCDELAY}" ]] && MONGODB_SYNCDELAY=""

declare -x MONGODB_REPAIRPATH
[[ -z "${MONGODB_REPAIRPATH}" ]] && MONGODB_REPAIRPATH=""

declare -x MONGODB_NOJOURNAL
[[ -z "${MONGODB_NOJOURNAL}" ]] && MONGODB_NOJOURNAL="false"

declare -x MONGODB_JOURNAL_OPTIONS
[[ -z "${MONGODB_JOURNAL_OPTIONS}" ]] && MONGODB_JOURNAL_OPTIONS=""

declare -x MONGODB_JOURNAL_COMMIT_INTERVAL
[[ -z "${MONGODB_JOURNAL_COMMIT_INTERVAL}" ]] && MONGODB_JOURNAL_COMMIT_INTERVAL=""

declare -x MONGODB_WIRED_TIGER_CACHE_SIZE
[[ -z "${MONGODB_WIRED_TIGER_CACHE_SIZE}" ]] && MONGODB_WIRED_TIGER_CACHE_SIZE=""

declare -x MONGODB_WIRED_TIGER_STATISTICS_LOG_DELAY
[[ -z "${MONGODB_WIRED_TIGER_STATISTICS_LOG_DELAY}" ]] && MONGODB_WIRED_TIGER_STATISTICS_LOG_DELAY=""

declare -x MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR
[[ -z "${MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR}" ]] && MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR=""

declare -x MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES
[[ -z "${MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES}" ]] && MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES=""

declare -x MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR
[[ -z "${MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR}" ]] && MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR=""

declare -x MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION
[[ -z "${MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION}" ]] && MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION=""

declare -x MONGODB_SKIP_CHOWN
[[ -z "${MONGODB_SKIP_CHOWN}" ]] && MONGODB_SKIP_CHOWN="false"

