#!/usr/bin/env bash

declare -x MONGODB_PERFORM_REPAIR
[[ -z "${MONGODB_PERFORM_REPAIR}" ]] && MONGODB_PERFORM_REPAIR="false"

declare -x MONGODB_PERFORM_UPGRADE
[[ -z "${MONGODB_PERFORM_UPGRADE}" ]] && MONGODB_PERFORM_UPGRADE="true"

declare -x MONGODB_ROOT_USERNAME
[[ -z "${MONGODB_ROOT_USERNAME}" ]] && MONGODB_ROOT_USERNAME=""

declare -x MONGODB_ROOT_PASSWORD
[[ -z "${MONGODB_ROOT_PASSWORD}" ]] && MONGODB_ROOT_PASSWORD=""

declare -x MONGODB_AUTH_DB
[[ -z "${MONGODB_AUTH_DB}" ]] && MONGODB_AUTH_DB="admin"

declare -x MONGODB_USERNAME
[[ -z "${MONGODB_USERNAME}" ]] && MONGODB_USERNAME=""

declare -x MONGODB_PASSWORD
[[ -z "${MONGODB_PASSWORD}" ]] && MONGODB_PASSWORD=""

declare -x MONGODB_DATABASE
[[ -z "${MONGODB_DATABASE}" ]] && MONGODB_DATABASE=""

declare -x MONGODB_NETWORK_MESSAGE_COMPRESSORS
[[ -z "${MONGODB_NETWORK_MESSAGE_COMPRESSORS}" ]] && MONGODB_NETWORK_MESSAGE_COMPRESSORS=""

declare -x MONGODB_CONFIG
[[ -z "${MONGODB_CONFIG}" ]] && MONGODB_CONFIG=""

declare -x MONGODB_CONFIG_EXPAND
[[ -z "${MONGODB_CONFIG_EXPAND}" ]] && MONGODB_CONFIG_EXPAND=""

declare -x MONGODB_IPV6
[[ -z "${MONGODB_IPV6}" ]] && MONGODB_IPV6="false"

declare -x MONGODB_LISTEN_BACKLOG
[[ -z "${MONGODB_LISTEN_BACKLOG}" ]] && MONGODB_LISTEN_BACKLOG=""

declare -x MONGODB_MAX_CONNS
[[ -z "${MONGODB_MAX_CONNS}" ]] && MONGODB_MAX_CONNS=""

declare -x MONGODB_TIMEZONE_INFO
[[ -z "${MONGODB_TIMEZONE_INFO}" ]] && MONGODB_TIMEZONE_INFO=""

declare -x MONGODB_VERBOSE
[[ -z "${MONGODB_VERBOSE}" ]] && MONGODB_VERBOSE="false"

declare -x MONGODB_QUIET
[[ -z "${MONGODB_QUIET}" ]] && MONGODB_QUIET="false"

declare -x MONGODB_TIMESTAMP_FORMAT
[[ -z "${MONGODB_TIMESTAMP_FORMAT}" ]] && MONGODB_TIMESTAMP_FORMAT=""

declare -x MONGODB_SET_PARAMETER
[[ -z "${MONGODB_SET_PARAMETER}" ]] && MONGODB_SET_PARAMETER=""

declare -x MONGODB_TRANSITION_TO_AUTH
[[ -z "${MONGODB_TRANSITION_TO_AUTH}" ]] && MONGODB_TRANSITION_TO_AUTH="false"

declare -x MONGODB_SLOWMS
[[ -z "${MONGODB_SLOWMS}" ]] && MONGODB_SLOWMS=""

declare -x MONGODB_SLOW_OP_SAMPLE_RATE
[[ -z "${MONGODB_SLOW_OP_SAMPLE_RATE}" ]] && MONGODB_SLOW_OP_SAMPLE_RATE=""

declare -x MONGODB_PROFILE_FILTER
[[ -z "${MONGODB_PROFILE_FILTER}" ]] && MONGODB_PROFILE_FILTER=""

declare -x MONGODB_CLUSTER_IP_SOURCE_WHITELIST
[[ -z "${MONGODB_CLUSTER_IP_SOURCE_WHITELIST}" ]] && MONGODB_CLUSTER_IP_SOURCE_WHITELIST=""

declare -x MONGODB_PROFILE
[[ -z "${MONGODB_PROFILE}" ]] && MONGODB_PROFILE=""

declare -x MONGODB_CPU
[[ -z "${MONGODB_CPU}" ]] && MONGODB_CPU="false"

declare -x MONGODB_SYSINFO
[[ -z "${MONGODB_SYSINFO}" ]] && MONGODB_SYSINFO="false"

declare -x MONGODB_NOSCRIPTING
[[ -z "${MONGODB_NOSCRIPTING}" ]] && MONGODB_NOSCRIPTING="false"

declare -x MONGODB_NOTABLESCAN
[[ -z "${MONGODB_NOTABLESCAN}" ]] && MONGODB_NOTABLESCAN="false"

declare -x MONGODB_KEY_FILE
[[ -z "${MONGODB_KEY_FILE}" ]] && MONGODB_KEY_FILE=""

declare -x MONGODB_CLUSTER_AUTH_MODE
[[ -z "${MONGODB_CLUSTER_AUTH_MODE}" ]] && MONGODB_CLUSTER_AUTH_MODE=""

declare -x MONGODB_OPLOG_SIZE
[[ -z "${MONGODB_OPLOG_SIZE}" ]] && MONGODB_OPLOG_SIZE=""

declare -x MONGODB_REPL_SET
[[ -z "${MONGODB_REPL_SET}" ]] && MONGODB_REPL_SET=""

declare -x MONGODB_ENABLE_MAJORITY_READ_CONCERN
[[ -z "${MONGODB_ENABLE_MAJORITY_READ_CONCERN}" ]] && MONGODB_ENABLE_MAJORITY_READ_CONCERN="false"

declare -x MONGODB_CONFIGSVR
[[ -z "${MONGODB_CONFIGSVR}" ]] && MONGODB_CONFIGSVR="false"

declare -x MONGODB_SHARDSVR
[[ -z "${MONGODB_SHARDSVR}" ]] && MONGODB_SHARDSVR="false"

declare -x MONGODB_STORAGE_ENGINE
[[ -z "${MONGODB_STORAGE_ENGINE}" ]] && MONGODB_STORAGE_ENGINE=""

declare -x MONGODB_DBPATH
[[ -z "${MONGODB_DBPATH}" ]] && MONGODB_DBPATH="/var/lib/mongodb"

declare -x MONGODB_DIRECTORYPERDB
[[ -z "${MONGODB_DIRECTORYPERDB}" ]] && MONGODB_DIRECTORYPERDB="false"

declare -x MONGODB_SYNCDELAY
[[ -z "${MONGODB_SYNCDELAY}" ]] && MONGODB_SYNCDELAY=""

declare -x MONGODB_JOURNAL_COMMIT_INTERVAL
[[ -z "${MONGODB_JOURNAL_COMMIT_INTERVAL}" ]] && MONGODB_JOURNAL_COMMIT_INTERVAL=""

declare -x MONGODB_NOJOURNAL
[[ -z "${MONGODB_NOJOURNAL}" ]] && MONGODB_NOJOURNAL="false"

declare -x MONGODB_OPLOG_MIN_RETENTION_HOURS
[[ -z "${MONGODB_OPLOG_MIN_RETENTION_HOURS}" ]] && MONGODB_OPLOG_MIN_RETENTION_HOURS=""

declare -x MONGODB_WIRED_TIGER_CACHE_SIZE
[[ -z "${MONGODB_WIRED_TIGER_CACHE_SIZE}" ]] && MONGODB_WIRED_TIGER_CACHE_SIZE=""

declare -x MONGODB_ZSTD_DEFAULT_COMPRESSION_LEVEL
[[ -z "${MONGODB_ZSTD_DEFAULT_COMPRESSION_LEVEL}" ]] && MONGODB_ZSTD_DEFAULT_COMPRESSION_LEVEL=""

declare -x MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR
[[ -z "${MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR}" ]] && MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR=""

declare -x MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES
[[ -z "${MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES}" ]] && MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES=""

declare -x MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR
[[ -z "${MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR}" ]] && MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR=""

declare -x MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION
[[ -z "${MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION}" ]] && MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION=""

declare -x MONGODB_AWS_IAM_SESSION_TOKEN
[[ -z "${MONGODB_AWS_IAM_SESSION_TOKEN}" ]] && MONGODB_AWS_IAM_SESSION_TOKEN=""

declare -x MONGODB_ENABLE_FREE_MONITORING
[[ -z "${MONGODB_ENABLE_FREE_MONITORING}" ]] && MONGODB_ENABLE_FREE_MONITORING="off"

declare -x MONGODB_FREE_MONITORING_TAG
[[ -z "${MONGODB_FREE_MONITORING_TAG}" ]] && MONGODB_FREE_MONITORING_TAG=""

declare -x MONGODB_SSL_ON_NORMAL_PORTS
[[ -z "${MONGODB_SSL_ON_NORMAL_PORTS}" ]] && MONGODB_SSL_ON_NORMAL_PORTS="false"

declare -x MONGODB_SSL_MODE
[[ -z "${MONGODB_SSL_MODE}" ]] && MONGODB_SSL_MODE=""

declare -x MONGODB_SSL_CERTIFICATE_KEY_FILE
[[ -z "${MONGODB_SSL_CERTIFICATE_KEY_FILE}" ]] && MONGODB_SSL_CERTIFICATE_KEY_FILE="${MONGODB_SSL_PEM_KEY_FILE}"

declare -x MONGODB_SSL_CERTIFICATE_KEY_FILE_PASSWORD
[[ -z "${MONGODB_SSL_CERTIFICATE_KEY_FILE_PASSWORD}" ]] && MONGODB_SSL_CERTIFICATE_KEY_FILE_PASSWORD="${MONGODB_SSL_PEM_KEY_PASSWORD}"

declare -x MONGODB_SSL_CLUSTER_FILE
[[ -z "${MONGODB_SSL_CLUSTER_FILE}" ]] && MONGODB_SSL_CLUSTER_FILE=""

declare -x MONGODB_SSL_CLUSTER_PASSWORD
[[ -z "${MONGODB_SSL_CLUSTER_PASSWORD}" ]] && MONGODB_SSL_CLUSTER_PASSWORD=""

declare -x MONGODB_SSL_CA_FILE
[[ -z "${MONGODB_SSL_CA_FILE}" ]] && MONGODB_SSL_CA_FILE=""

declare -x MONGODB_SSL_CLUSTER_CA_FILE
[[ -z "${MONGODB_SSL_CLUSTER_CA_FILE}" ]] && MONGODB_SSL_CLUSTER_CA_FILE=""

declare -x MONGODB_SSL_CRL_FILE
[[ -z "${MONGODB_SSL_CRL_FILE}" ]] && MONGODB_SSL_CRL_FILE=""

declare -x MONGODB_SSL_DISABLED_PROTOCOLS
[[ -z "${MONGODB_SSL_DISABLED_PROTOCOLS}" ]] && MONGODB_SSL_DISABLED_PROTOCOLS=""

declare -x MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES
[[ -z "${MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES}" ]] && MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES="false"

declare -x MONGODB_SSL_ALLOW_INVALID_HOSTNAMES
[[ -z "${MONGODB_SSL_ALLOW_INVALID_HOSTNAMES}" ]] && MONGODB_SSL_ALLOW_INVALID_HOSTNAMES="false"

declare -x MONGODB_SSL_ALLOW_INVALID_CERTIFICATES
[[ -z "${MONGODB_SSL_ALLOW_INVALID_CERTIFICATES}" ]] && MONGODB_SSL_ALLOW_INVALID_CERTIFICATES="false"

declare -x MONGODB_SSL_FIPS_MODE
[[ -z "${MONGODB_SSL_FIPS_MODE}" ]] && MONGODB_SSL_FIPS_MODE="false"

declare -x MONGODB_SSL_LOG_VERSIONS
[[ -z "${MONGODB_SSL_LOG_VERSIONS}" ]] && MONGODB_SSL_LOG_VERSIONS=""

declare -x MONGODB_NOAUTH
[[ -z "${MONGODB_NOAUTH}" ]] && MONGODB_NOAUTH="false"

declare -x MONGODB_AUTH
[[ -z "${MONGODB_AUTH}" ]] && MONGODB_AUTH="false"

declare -x MONGODB_SKIP_CHOWN
[[ -z "${MONGODB_SKIP_CHOWN}" ]] && MONGODB_SKIP_CHOWN="false"

true
