FROM ghcr.io/dockhippie/ubuntu:22.04-amd64@sha256:826893af245b2a971fecb3c042d097fc67b35b64253eefba7591740c11db9b2b

VOLUME ["/var/lib/mongodb", "/var/lib/backup"]
EXPOSE 27017 27018 27019

WORKDIR /var/lib/mongodb
CMD ["/usr/bin/container"]

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSLo- https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add - && \
  echo "deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb.list && \
  apt-get update && \
  apt-get upgrade -y && \
  mkdir -p /var/lib/mongodb && \
  groupadd -g 1000 mongodb && \
  useradd -u 1000 -d /var/lib/mongodb -g mongodb -s /bin/bash -m mongodb && \
  apt-get install -y mongodb-org jq && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get autoremove -y && \
  apt-get clean -y && \
  rm -rf /var/lib/apt/lists/* /var/lib/mongodb/*

COPY ./overlay /
