FROM webhippie/alpine:latest@sha256:d36a8c2be25705ba06c33bb67a14a721ae0036c30f5a13d0b83b0210c953f66b

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="MongoDB" \
  org.label-schema.vcs-url="https://github.com/dockhippie/mongodb.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 27017 27018 27019

VOLUME ["/var/lib/mongodb", "/var/lib/backup"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/mongodb && \
  groupadd -g 1000 mongodb && \
  useradd -u 1000 -d /var/lib/mongodb -g mongodb -s /bin/bash -m mongodb && \
  apk add mongodb mongodb-tools jq && \
  rm -rf /var/cache/apk/* /var/lib/mongodb/*

COPY ./overlay ./overlay-amd64 /
